# THIS IS THE DOCKER COMPOSE I’M USING
# DO NOT USE IT TO DEPLOY THE BOT
version: '3.8'

services:
  bot:
    build: .
    image: in-house-queue
    environment:
      TOKEN: ${TOKEN}
      TOP_GG_TOKEN: ${TOP_GG_TOKEN}
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - inhouse-db:/app/db
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - dozzle
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_network

  backup:
    image: offen/docker-volume-backup:v2
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S-${AWS_S3_PATH}.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_CRON_EXPRESSION: "0 0 * * *"
      BACKUP_RETENTION_DAYS: "30"
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_PATH: ${AWS_S3_PATH}
    volumes:
      - inhouse-db:/backup/inhouse-db-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      DOZZLE_USERNAME: ${DOZZLE_USERNAME}
      DOZZLE_PASSWORD: ${DOZZLE_PASSWORD}
      DOZZLE_NO_ANALYTICS: "True"
      DOZZLE_HOSTNAME: ${DOZZLE_HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  inhouse-db:
  certbot-etc:
  certbot-var:
