name: Back Up DB
on:
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}-live
jobs:
  backup-db:
    name: Backup DB
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/${{ env.REPO_NAME }}/db || exit
          DATE=$(date '+%Y-%m-%d-%H:%M:%S')
          sqlite3 main.sqlite ".backup m_database-${DATE}.sq3.bak"
          mv m_database-${DATE}.sq3.bak /root/s3-bucket/${{ env.REPO_NAME }}
