name: Update Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
  backup-db:
      needs: deploy-via-sftp
      runs-on: ubuntu-latest
      steps:
        - id: creating-systemctl-service
          uses: fifsky/ssh-action@master
          with:
            command: |
              cd ${{ env.REPO_NAME }} || exit
              DATE=$(date '+%Y-%m-%d-%H:%M:%S')
              sqlite3 main.sqlite ".backup m_database-${DATE}.sq3.bak"
              mv m_database-${DATE}.sq3.bak /root/s3-bucket/${{ env.REPO_NAME }}
            host: ${{ secrets.HOST }}
            user: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: ${{ secrets.HOST }}
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./*
          remote_path: /root/${{ env.REPO_NAME }}/
          args: '-o ConnectTimeout=5'
          
  restart-bot:
    needs: [deploy-via-sftp]
    runs-on: ubuntu-latest
    steps:
      - id: creating-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          command: sudo systemctl start ${{ env.REPO_NAME }}-watcher.service
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
